name: lambda-deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '1.18' # The Go version to download (if necessary) and use.
          check-latest: true
          cache: true
          cache-dependency-path: go.sum
      - run: go version
      - name: Get dependencies
        run: go get -v -t -d ./...

      - name: Test code
        run: go test -v .

      - name: build app
        run: make

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: upload main.zip to s3
        run: aws s3 cp main.zip s3://deploy-gin-helloworld

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Update Lambda function
        run: |
          aws lambda update-function-code --function-name gin-helloworld --s3-bucket deploy-gin-helloworld --s3-key main.zip\
          | jq '.FunctionName, .LastUpdateStatus'